# Generated by Django 4.2 on 2023-06-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('campany', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='Testimonals/')),
                ('feedback', models.CharField(max_length=10000)),
            ],
        ),
    ]
