# Generated by Django 4.2 on 2023-06-27 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_abouts_brands_contacts_skills_workexperience_works_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Abouts',
            new_name='About',
        ),
        migrations.RenameModel(
            old_name='Brands',
            new_name='Brand',
        ),
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
        migrations.RenameModel(
            old_name='Experiences',
            new_name='Experience',
        ),
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
        migrations.RenameModel(
            old_name='Testimonals',
            new_name='Testimonal',
        ),
        migrations.RenameModel(
            old_name='Works',
            new_name='Work',
        ),
    ]
